spring.application.name=website-petHospital-project

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=javauser
spring.datasource.password=java1234

# classpath 뒤에 *를 붙여 하위 경로의 XML을 확실히 스캔하도록 변경
mybatis.mapper-locations=classpath*:mapper/**/*.xml