spring.application.name=website-petHospital-project

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=javauser
spring.datasource.password=java1234

# classpath 뒤에 *를 붙여 하위 경로의 XML을 확실히 스캔하도록 변경
mybatis.mapper-locations=classpath*:mapper/**/*.xml

# MyBatis Mapper XML에서 DTO의 전체 패키지명 대신 클래스명만 사용하도록 설정
mybatis.type-aliases-package=com.spring.website.pethp.dto

# resultmap 생략가능
mybatis.configuration.map-underscore-to-camel-case=true
